/automated_reporting/scripts/generate_report.py:13: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
✅ Report generato con successo!
Traceback (most recent call last):
  File "/home/vboxuser/automated_reporting/scripts/generate_report.py", line 1, in <module>
    from sqlalchemy import create_engine
ModuleNotFoundError: No module named 'sqlalchemy'
✅ Email inviata con successo!
